# Generated by Django 6.0.2 on 2026-02-24 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='property',
            name='moderation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Новое бронирование'), ('booking_paid', 'Бронирование оплачено'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('booking_completed', 'Бронирование завершено'), ('contract_signed', 'Договор подписан'), ('review_added', 'Добавлен отзыв'), ('message_received', 'Новое сообщение'), ('system', 'Системное уведомление')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активно'), ('rejected', 'Отклонено'), ('inactive', 'Неактивно')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('property', 'user', 'booking')},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='PDF файл')),
                ('signed_by_tenant', models.BooleanField(default=False, verbose_name='Подписан арендатором')),
                ('signed_by_landlord', models.BooleanField(default=False, verbose_name='Подписан арендодателем')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало бронирования')),
                ('end_datetime', models.DateTimeField(verbose_name='Окончание бронирования')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Количество гостей')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property', verbose_name='Помещение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'unique_together': {('user', 'property', 'start_datetime', 'end_datetime')},
            },
        ),
    ]
