# Generated by Django 6.0.2 on 2026-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_unique_together_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='moderation_comment',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Новое бронирование'), ('booking_paid', 'Бронирование оплачено'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('booking_completed', 'Бронирование завершено'), ('contract_signed', 'Договор подписан'), ('review_added', 'Добавлен отзыв'), ('review_approved', 'Отзыв одобрен'), ('review_rejected', 'Отзыв отклонен'), ('property_approved', 'Помещение одобрено'), ('property_rejected', 'Помещение отклонено'), ('message_received', 'Новое сообщение'), ('system', 'Системное уведомление')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
