# Generated by Django 6.0.2 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_property_moderation_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('status_change', 'Смена статуса'), ('moderation', 'Модерация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Действие')),
                ('target_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('target_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Объект')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='core.user', verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Лог аудита админки',
                'verbose_name_plural': 'Логи аудита админки',
                'ordering': ['-created_at'],
            },
        ),
    ]
