# Generated by Django 6.0.2 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='Логин (снимок)')),
                ('event_type', models.CharField(choices=[('register', 'Регистрация'), ('login_success', 'Успешный вход'), ('login_failed', 'Ошибка входа'), ('logout', 'Выход'), ('profile_update', 'Обновление профиля'), ('password_change', 'Смена пароля'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Событие')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог пользовательского аудита',
                'verbose_name_plural': 'Логи пользовательского аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
